### ISSUE TITLE
Fix HTTP/HTTPS issue

### ISSUE THREAD

**Issue by treyhunner** [TruthfulTechnology/unicode.party#21]
There's two protocols that both work. Maybe we should just redirect all HTTP to HTTPS?

Issue reported by @dalanmiller. :bow:

**Comment by dalanmiller** [comment]
How are you currently deploying this app?

**Comment by treyhunner** [comment]
It's deployed into and hosted from an Amazon S3 bucket via ember-cli-deploy plugins.

**Comment by dalanmiller** [comment]
Looks like you want to set this in CloudFront - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/SecureConnections.html

> To require HTTPS between CloudFront and your origin (optional): Configure the Origin Protocol Policy for one or more CloudFront origins either to require that CloudFront fetches objects from your origin by using HTTPS or to require that CloudFront uses the protocol that the viewer used to request the objects. For example, if you choose Match Viewer for the Origin Protocol Policy and the viewer uses HTTPS to request an object from CloudFront, CloudFront also uses HTTPS to forward the request to your origin. When your origin is an Amazon S3 bucket, Match Viewer is the default setting and cannot be changed.

**Comment by singingwolfboy** [comment]
I just wrote a tutorial about deploying static sites on Amazon S3, and it also covers setting up HTTPS via CloudFront and Certificate Manager. Check it out! https://www.davidbaumgold.com/tutorials/deploy-static-site-aws-s3-cloudfront/

**Comment by treyhunner** [comment]
This is now resolved. Hosting changed to Netlify from S3, but also I set CloudFlare to force HTTPS.
