### ISSUE TITLE
letter-spacing breaks flags (Firefox + emojione)

### ISSUE THREAD

**Issue by bmispelon** [TruthfulTechnology/unicode.party#22]
Here's what I see in my browser when I search for flags:

![unicode_party_the_unicode_emoji_search_engine_-_2016-06-20_12 24 18](https://cloud.githubusercontent.com/assets/6345/16192653/77a260d4-36e2-11e6-8ae4-c7792507545b.png)

If I disable the [`letter-spacing` property](https://github.com/TruthfulTechnology/unicode.party/blob/7e4bda7501fdd5c00cbdc79512bafb1fe5704607/app/styles/_typography.scss#L68) in the inspector, then the display is correct again:

![unicode_party_the_unicode_emoji_search_engine_-_2016-06-20_12 24 51](https://cloud.githubusercontent.com/assets/6345/16192689/a52e5dd2-36e2-11e6-83f4-f6bb77825520.png)

I'm using Firefox on Linux (with emojione so I can get full-color emoji in Firefox).

**Comment by bmispelon** [comment]
The same issue appears for all multi-char emojis by the way, see this example with the "family-*" emojis: http://unicode.party/?query=family

I think the fix should be to apply `letter-spacing: normal` to the characters but the current behavior seems to have been introduced on purpose (in 7e4bda7501fdd5c00cbdc79512bafb1fe5704607) so I'm not sure if that would break other things.

**Comment by treyhunner** [comment]
I'm not seeing this issue but my emoji look different. I believe I'm also
using emojione, but maybe a different version.

Removing letter-spacing doesn't seem to break things for my use case right
now, so I'll do that for now.

On Mon, Jun 20, 2016 at 5:43 AM Baptiste Mispelon <notifications@github.com>
wrote:

> The same issue appears for all multi-char emojis by the way, see this
> example with the "family-*" emojis: http://unicode.party/?query=family
>
> I think the fix should be to apply letter-spacing: normal to the
> characters but the current behavior seems to have been introduced on
> purpose (in 7e4bda7
> <https://github.com/TruthfulTechnology/unicode.party/commit/7e4bda7501fdd5c00cbdc79512bafb1fe5704607>)
> so I'm not sure if that would break other things.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TruthfulTechnology/unicode.party/issues/22#issuecomment-227131427>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AARaqKmX8gBBTeHAio6OAUXmA1BW1_cEks5qNorigaJpZM4I5m7y>
> .
>
-- 
Trey Hunner
Python Trainer, http://Truthful.Technology
Director, Python Software Foundation
I host live online python chats: http://WeeklyPython.Chat
