### ISSUE TITLE
[feature request] Allow specifying preferred skin color modifier

### ISSUE THREAD

**Issue by bmispelon** [TruthfulTechnology/unicode.party#23]
Unless I'm mistaken, there's currently no way to set a skin color modifier (I can't even find the modifiers when I search).

Ideally, you could somehow specify your favorite fitzpatrick modifier (stored in a cookie?) and then all relevant emoji (not sure how to characterize those) would be copied along with this modifier.

What do you think?

**Comment by treyhunner** [comment]
That sounds neat. I agree that a universal switch would be cool.
