### ISSUE TITLE
Unicode party hosting service ?

### ISSUE THREAD

**Issue by Sim4n6** [TruthfulTechnology/unicode.party#47]
where do you host unicode party please ?

**Comment by treyhunner** [comment]
Amazon S3

**Comment by Sim4n6** [comment]
Amazon S3 file hosting services and the domain provider is something else right ?

**Comment by Sim4n6** [comment]
Thank you for the explanation

**Comment by treyhunner** [comment]
Yes. Pretty sure DNS is Cloudflare. It's all a static site, so no back end needed.

**Comment by Sim4n6** [comment]
To be honest there is a niche in the hosting area, and a difficult step to overcome from for instance django web development to putting it live too the wild
